[tool.poetry]
name = "robotics_toolbox"
version = "0.0.0"
description = "Robotics toolbox used to teach basic robotics at CTU."
authors = ["Vladimir Petrik <vladimir.petrik@cvut.cz>"]
license = "BSD-3-Clause license"
readme = "README.md"
packages = [{include = "robotics_toolbox"}]

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.7.1"
numpy = "^1.24.0"
robomeshcat = "^1.1.1"
pin = "^2.6.19"
example-robot-data = "^4.0.8"
pycollada = "^0.7.2"
shapely = "^2.0.1"
anytree = "^2.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
ruff = "^0.0.260"
black = "^23.3.0"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
